[build]
  publish = "."            # publica la raíz (ahí están /app-assets y /starter-kit)
  command = "echo no-build"

[build.environment]
  NETLIFY_SKIP_INSTALL = "true"   # << clave: NO instales npm
  NODE_VERSION = "18"             # por si algún script usa Node
